using System;
using NHSE.Core;

namespace SysBot.ACNHOrders
{
    [Serializable]
    public class OrderBotConfig : IConfigItem
    {
        private int _maxQueueCount = 50;
        private int _timeAllowed = 180;

        /// <summary> Amount of times to perform a pick-up item action. </summary>
        public int MaxQueueCount
        {
            get => _maxQueueCount;
            set => _maxQueueCount = Math.Max(1, Math.Min(99, value));
        }

        /// <summary> Maximum amount of time before a user is kicked from your island to avoid loiterers. Minimum is 3 minutes (180 seconds) </summary>
        public int UserTimeAllowed 
        { 
            get => _timeAllowed; 
            set => Math.Max(180, value); 
        }

        /// <summary>
        /// Wraps all items generated by the bot.
        ///  </summary>
        public bool WrapAllItems { get; set; } = false; // doesn't wrap DIY recipes

        /// <summary> Wrapping paper to apply when <see cref="WrapAllItems"/> is true. </summary>
        public ItemWrappingPaper WrappingPaper { get; set; } = ItemWrappingPaper.White;
    }
}
